PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rep: <http://www.openrdf.org/config/repository#>
PREFIX sr: <http://www.openrdf.org/config/repository/sail#>
PREFIX sail: <http://www.openrdf.org/config/sail#>
PREFIX sys: <http://www.openrdf.org/config/repository#>
PREFIX ns: <http://www.openrdf.org/config/sail/native#>

INSERT DATA {
  _:node001 a sys:RepositoryContext .
  GRAPH _:node001 {
    [] a rep:Repository ;
      rep:repositoryID "smartweb" ;
      rdfs:label "SmartWeb Store" ;
      rep:repositoryImpl [
        rep:repositoryType "openrdf:SailRepository" ;
        sr:sailImpl [
          sail:sailType "openrdf:NativeStore" ;
          ns:tripleIndexes "spoc,posc"
        ]
      ].
  }

}
